### ISSUE TITLE
potential lookahead bias

### ISSUE THREAD

**Issue by mg64ve** [Draichi/altcoin-bot-advisor#11]
Nice work, thanks for sharing.
I was looking to your step function:

```
    def step(self, action):
        # Execute one time step within the environment
        self._take_action(action)
        self.current_step += 1

        net_worth_and_buyhold_mean = (self.net_worth + self.buy_and_hold) / 2
        reward = (self.net_worth - self.buy_and_hold) / net_worth_and_buyhold_mean
        done = self.net_worth <= 0 or self.balance <= 0 or self.current_step >= len(self.df1_features.loc[:, 'open'].values) -1
        obs = self._next_observation()

return obs, reward, done, {}

```

this calculate reward from values saved one step back.
Don't you think this is a lookahead bias?

**Comment by Draichi** [comment]
Sorry, can you elaborate? Where exactly in the step function?

Thanks

**Comment by mg64ve** [comment]
What I mean is that in the step function you:

1. take an action
2. increment time step
3. calculate the reward with some variables that you set before incrementing timestep

That's why I guess you are calculating the reward based on data you already had in your dataset when you predicted the next action.
Do you agree?

**Comment by Draichi** [comment]
Ok, now I understand.

What's happening is the reward needs to be calculated after the action so the price can change and we can compute how bad/good that action was.

In a real world scenario, lets say trading with hourly data, I would have a scheduler task to take an action at timestep t, and in the next hour (t+1), compute its reward.

**Comment by mg64ve** [comment]
Ok @Draichi .
Are you going to change it?

**Comment by Draichi** [comment]
I don't know how... I'm still reading about lookahead bias, any idea?

**Comment by mg64ve** [comment]
I am not sure if we can say that this is a proper lookahead bias.
I think you are rewarding your agent with a reward that is already known at the moment of predicting next action.
That means this algorithm will tend to predict action that might not have a reward at next step.
I think environment/agent python classes are very much prone to this type of error.
Please take your time to make in deep analysis and let me know if my thoughts are right or not.
Thanks @Draichi 
Best regards.

**Comment by cuda2625403** [comment]
I think it is ok , no lookahead bias.
