### ISSUE TITLE
Decouple reward function

### ISSUE THREAD

**Issue by cuda2625403** [Draichi/altcoin-bot-advisor#14]
I check  self.trades  in core_env.py , self.trades data  caculate is  loss,but  total reward  display Positive profit! thank  you

**Comment by Draichi** [comment]
Can you share where in the code exactly this is happening?

**Comment by cuda2625403** [comment]
```py
 def _compute_trade(self):
        for asset in self.assets_list:
            if self.shares_sold[asset] > 0 or self.shares_bought[asset] > 0:
                self.trades[asset].append({
                    'step': self.current_step,
                    'amount': self.shares_sold[asset] if self.shares_sold[asset] > 0 else self.shares_bought[asset],
                    'total': self.sales if self.shares_sold[asset] > 0 else self.cost,
                    'type': 'sell' if self.shares_sold[asset] > 0 else 'buy',
                    'current_price': self.current_price[asset]	
                })
```

**Comment by Draichi** [comment]
self.trades do not calculate the loss, it only append the transaction.

the reward is calculated as follows:
```py
net_worth_and_buyhold_mean = (self.net_worth + self.buy_and_hold) / 2
reward = (self.net_worth - self.buy_and_hold) / net_worth_and_buyhold_mean
```

**Comment by cuda2625403** [comment]
but self.trades  record transaction ,I can manual calculated  the loss by  dump self.trades  to csv file

**Comment by Draichi** [comment]
the reward is positive because its been compared to the buy and hold strategy

it would be nice to have a decoupled reward function so we can plug and play different reward functions and see which one is the best
