### ISSUE TITLE
PyStan StanModel error

### ISSUE THREAD

**Issue by Prossi79** [Draichi/altcoin-bot-advisor#2]
Hello Draichi!

A few days ago I have downloaded your very interesting project but got issues to execute forecast.py (Pyhton 3.6, Windows 10) - following error message:

WARNING:pystan:No module named 'stanfit4anon_model_861b75c6337e237650a61ae58c4385ef_2841341000846931969'
WARNING:pystan:Something went wrong while unpickling the StanModel. Consider recompiling.

Traceback (most recent call last):
  File "forecast.py", line 20, in <module>
    df_prophet.fit(df)
  File "C:\Users\Andreas Prosswimmer\Anaconda3\envs\crypto_env\lib\site-packages\fbprophet\forecaster.py", line 1105, in fit
    params = model.optimizing(**args)
  File "C:\Users\Andreas Prosswimmer\Anaconda3\envs\crypto_env\lib\site-packages\pystan\model.py", line 511, in optimizing
    fit = self.fit_class(data, seed)
AttributeError: 'StanModel' object has no attribute 'fit_class'

__________________________

Lookig forward testing your code!

**Comment by Draichi** [comment]
Hello mate, thanks. It seems like `pystan` have different install methods for ubuntu and windows [see here](https://pystan.readthedocs.io/en/latest/windows.html). This project is, so far, tested on ubuntu only.

If you doesn't like the idea of installing linux, you can use it on a virtual machine like viratualbox

**Comment by Draichi** [comment]
Check out the readme update, Windows is supported now.
