### ISSUE TITLE
T2000 - the T1000 reborn ?

### ISSUE THREAD

**Issue by doftorul** [Draichi/altcoin-bot-advisor#21]
R u really refactoring it ?
Need any help ?

**Comment by Draichi** [comment]
Yeas I am :)

A lil help would be good for sure 😊

I'm replacing pandas csv by SQLite tables so the data fetching by the model would be faster.


Next step is to make T1000 installable via pip, do you think you can take care of this one?

Thanks bother 
I appreciate

**Comment by doftorul** [comment]
I can definitely try to do my best.
What'll be the name of the package ?

**Comment by Draichi** [comment]
Thank you

I have no idea :grin:
