### ISSUE TITLE
AttributeError: 'StanModel' object has no attribute 'fit_class'

### ISSUE THREAD

**Issue by Prossi79** [Draichi/altcoin-bot-advisor#3]
Trying to run the forecast.py on Ubuntu 18.04 (Mate desktop)- following error:

> loading bitcoin from cache
> loading nano from cache
> loading ripple from cache

Using TensorFlow backend.
/root/anaconda3/envs/crypto_env/lib/python3.6/site-packages/tensorflow/python/util/tf_inspect.py:75: DeprecationWarning:

inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()

INFO:fbprophet.forecaster:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
Traceback (most recent call last):
  File "forecast.py", line 20, in <module>
    df_prophet.fit(df)
  File "/root/anaconda3/envs/crypto_env/lib/python3.6/site-packages/fbprophet/forecaster.py", line 1003, in fit
    dat, init=stan_init, iter=1e4, **kwargs)
  File "/root/anaconda3/envs/crypto_env/lib/python3.6/site-packages/pystan/model.py", line 512, in optimizing
    fit = self.fit_class(data, seed)
AttributeError: 'StanModel' object has no attribute 'fit_class'

**Comment by Draichi** [comment]
I can't reproduce this error on my ubuntu 16.04, but it seems like a problem with pystan, try reinstall pystan (or downgrade to v2.17.1.0, they realese a update recently) and run a simple code with only [fbprophet](https://facebook.github.io/prophet/docs/quick_start.html) because the bug occours when you're calling fbprophet code.

**Comment by Draichi** [comment]
I push'd https://github.com/Draichi/cryptocurrency_prediction/commit/0f2ec54d4c86f2bd86ef172908634d2e26d1d65b a yml with a "stable" enviroment.

Try create a brand new env and tell me if works.
```
sudo apt-get install gcc g++ build-essential python-dev python3-dev
# make sure you have these installed

conda env create -f environment.yml
# create env
```
