### ISSUE TITLE
Test data same as train?

### ISSUE THREAD

**Issue by evanatyourservice** [Draichi/altcoin-bot-advisor#6]
Is Fig 1 a test run on the same data used to train the model?

**Comment by Draichi** [comment]
No, so far we are only training the agent, the image shows the  agent's learning curve

**Comment by evanatyourservice** [comment]
I’m sorry, I’m an idiot and made this issue in the wrong repository. Your work looks great Lucas!

**Comment by Draichi** [comment]
Don't worry brother, thank you.

**Comment by evanatyourservice** [comment]
Have you tried using rllib’s "model": {"use_lstm": true}?
