### ISSUE TITLE
init_data

### ISSUE THREAD

**Issue by evanatyourservice** [Draichi/altcoin-bot-advisor#8]
Might think of leaving df as pandas dataframe until end of step to speed up iterations through the list.

**Comment by Draichi** [comment]
have you tried it that way?

The reason for using a list instead of a pandas df is actually boosting performance.

**Comment by evanatyourservice** [comment]
I think I saw the slowdown when I started using long csv's with long episodes. Splitting the episodes into smaller pieces brought back speed.
