### ISSUE TITLE
a few issues

### ISSUE THREAD

**Issue by ss2cp** [Draichi/altcoin-bot-advisor#9]
Hi Lucas!

I found your repo from Adam King's project. First of all, great work and respect.

While my mac is training, there is a few issues I ran into. 

1. When installing env with conda on my mac, `matplotlib=2.2.3=py35h0e0179f_0` cannot be found. 
I removed the last part `py35h ...` and it fixed the problem.
So, my question is: _did you test this in ubuntu env, or mac?_

2. I tried to train multi model as instructed on `readme`, `python train_multi_model.py` gave me error not finding `SYMBOL_1` (from `vars.py`) 
I looked into what might caused this, but I could not find where you pass in the `SYMBOL`s from `vars.py`
_any idea how to fix this? or I did something wrong_

3. While I was looking into `train_multi_model.py`, I noticed in `experiment_spec`, there is a line `"local_dir": '/home/lucas/Documents/cryptocurrency_prediction/tensorboard'`.
I could not run this `train_multi_model.py` file, but if I did, I imagine it would give me an error about folder not exist. 

4. So instead I tried the second command you provided, `# single pair
python train.py \
        --algo PPO \
        --pair XRP/USDT \` and it is still running as I am writing this post. But I could not find where is the output `tensorflow` folder, so I cannot really track its progress. 
_Again, any idea? or did I do something wrong...?_

Again, great project! Thx!

**Comment by Draichi** [comment]
Hey mate, let me try to clarify things for you

1. I only tested in ubuntu, the mac.yml is a contribution from a mac user.

2. In `train_multi_model.py` the following line is missing:
```python
from configs.vars import *
```

3. Yeah you need to create a `tensorboard` folder and update "local_dir" to this recent create tensorboard folder (u do this if you want to save the checkpoints in the project root folder, if not, use the number 4 idea)

4. If you don't use the `"local_dir"` line your checkpoints will be saved at `~/ray_results/[EXPERIMENT_NAME]` by default.

I know the project is a lil messy, my wish now is to organize it but I'm working in something else and I have no time at the moment, so fell free to contribute if you want and any question let me know.

Thanks :smile:

**Comment by Draichi** [comment]
fixed https://github.com/Draichi/cryptocurrency_algotrading/commit/b3ef2ec220cc7d95a21ee548c176bcb2b2c89e2b

thanks for the catch
